# Generated by Django 6.0.4 on 2026-04-26 07:26

import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('middle_initial', models.CharField(blank=True, max_length=1, null=True)),
                ('suffix', models.CharField(blank=True, max_length=10, null=True)),
                ('contact_number', models.CharField(max_length=20)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_title', models.CharField(max_length=150)),
                ('project_type', models.CharField(max_length=50)),
                ('project_nature', models.CharField(max_length=50)),
                ('project_tenure', models.CharField(max_length=50)),
                ('project_cost', models.DecimalField(decimal_places=2, max_digits=15)),
                ('project_address', models.CharField(max_length=200)),
                ('project_barangay', models.CharField(max_length=100)),
                ('area_lot', models.DecimalField(decimal_places=2, max_digits=10)),
                ('area_improvement', models.DecimalField(decimal_places=2, max_digits=10)),
                ('area_bldg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('existing_use', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('applicant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('house_street', models.CharField(max_length=100)),
                ('barangay', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('personnel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('personnel_role', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('application_id', models.AutoField(primary_key=True, serialize=False)),
                ('application_status', models.CharField(max_length=50)),
                ('review_status', models.CharField(max_length=50)),
                ('application_comply', models.BooleanField(default=False)),
                ('application_completion', models.BooleanField(default=False)),
                ('application_endorsement', models.BooleanField(default=False)),
                ('applicant_type', models.CharField(choices=[('Individual', 'Individual'), ('Corporation', 'Corporation')], max_length=50)),
                ('corp_name', models.CharField(blank=True, max_length=100, null=True)),
                ('corp_address', models.CharField(blank=True, max_length=200, null=True)),
                ('corp_telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('right_over_land', models.CharField(choices=[('Owner', 'Owner'), ('Leased', 'Leased'), ('NotLot_Owner', 'Not-Lot Owner')], max_length=50)),
                ('authorized', models.BooleanField(default=False)),
                ('absoluteowner_first_name', models.CharField(max_length=50)),
                ('absoluteowner_last_name', models.CharField(max_length=50)),
                ('absoluteowner_middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('absoluteowner_suffix', models.CharField(blank=True, max_length=10, null=True)),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_applications', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.project')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment_type', models.CharField(max_length=50)),
                ('comment_box', models.TextField()),
                ('comment_timestamp', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.application')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('document_id', models.AutoField(primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('report_document', 'Report Document'), ('lot_title', 'Lot Title'), ('survey_plan', 'Survey Plan'), ('tax_dec', 'Tax Declaration'), ('tax_clear', 'Tax Clearance'), ('brgy_const_clear', 'Barangay Construction Clearance'), ('deed_of_sale', 'Deed of Sale'), ('auth_letter', 'Authorization Letter'), ('letter_exception', 'Letter of Exception'), ('draw_plan', 'Drawing Plan'), ('app_fr_bldg_permit', 'Application for Building Permit'), ('cost_est', 'Cost Estimate'), ('struc_analysis', 'Structural Analysis'), ('loc_clear_app_form', 'Locational Clearance Application Form'), ('loc_clear_cert', 'Locational Clearance Certificate')], max_length=50)),
                ('uploaded_document', models.FileField(upload_to='documents/')),
                ('upload_timestamp', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.application')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('report_type', models.CharField(max_length=50)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.application')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.document')),
            ],
        ),
        migrations.CreateModel(
            name='Syslog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=100)),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('channel', models.CharField(default='web', max_length=20)),
                ('status', models.CharField(default='unread', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.application')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('source_event_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.syslog')),
            ],
        ),
    ]
