# Generated by Django 6.0.4 on 2026-04-14 16:53

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('middle_initial', models.CharField(blank=True, max_length=1, null=True)),
                ('suffix', models.CharField(blank=True, max_length=10, null=True)),
                ('contact_number', models.CharField(max_length=20)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('application_id', models.AutoField(primary_key=True, serialize=False)),
                ('applicant_type', models.CharField(max_length=50)),
                ('corp_name', models.CharField(blank=True, max_length=100, null=True)),
                ('corp_address', models.CharField(blank=True, max_length=200, null=True)),
                ('right_of_land', models.CharField(max_length=100)),
                ('absoluteowner_suffix', models.CharField(blank=True, max_length=10, null=True)),
                ('absoluteowner_first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('absoluteowner_last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('absoluteowner_middle_initial', models.CharField(blank=True, max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_title', models.CharField(max_length=150)),
                ('project_type', models.CharField(max_length=50)),
                ('project_nature', models.CharField(max_length=50)),
                ('project_cost', models.DecimalField(decimal_places=2, max_digits=15)),
                ('project_location', models.CharField(max_length=200)),
                ('project_address', models.CharField(max_length=200)),
                ('project_barangay', models.CharField(max_length=100)),
                ('area_lot', models.DecimalField(decimal_places=2, max_digits=10)),
                ('area_improvement', models.DecimalField(decimal_places=2, max_digits=10)),
                ('area_bldg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('existing_use', models.CharField(max_length=100)),
                ('tax_dec_no', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('applicant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('house_street', models.CharField(max_length=100)),
                ('barangay', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('personnel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('personnel_role', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('document_id', models.AutoField(primary_key=True, serialize=False)),
                ('document_type', models.CharField(max_length=50)),
                ('uploaded_document', models.CharField(max_length=255)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='api.application')),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='api.project'),
        ),
        migrations.CreateModel(
            name='Syslog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syslogs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='api.applicant'),
        ),
        migrations.CreateModel(
            name='Remark',
            fields=[
                ('remark_id', models.AutoField(primary_key=True, serialize=False)),
                ('remark_desc', models.TextField()),
                ('remark_type', models.CharField(blank=True, max_length=50, null=True)),
                ('remark_datetime', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remarks', to='api.application')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remarks', to='api.personnel')),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationReport',
            fields=[
                ('decision_id', models.AutoField(primary_key=True, serialize=False)),
                ('eval_timestamp', models.DateTimeField()),
                ('decision_type', models.CharField(max_length=50)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_reports', to='api.application')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_reports', to='api.document')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_reports', to='api.personnel')),
            ],
        ),
    ]
