# Generated by Django 6.0.4 on 2026-04-19 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_customuser_managers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='syslog',
            old_name='timestamp',
            new_name='logged_at',
        ),
    ]
